[package]
name = "asm_unroll"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
# Don't need 'em :p
# quote = "1.0.36"
# syn = { version = "2.0.65", features = ["full", "extra-traits"] }