[package]
name = "asm_unroll"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/RedRam567/asm_unroll"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
# does not depend on syn or quote